Metrics/AbcSize:
  Enabled: false

Metrics/BlockNesting:
  Max: 4

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
   Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FileName:
  Exclude:
    - 'lib/vagrant-oneandone.rb'
    - 'vagrant-spec.config.rb'

