language: ruby
sudo: false

cache: bundler

branches:
  only:
    - master
rvm:
  - 2.2.5

before_install:
  - rvm @global do gem uninstall bundler --all --force --executables
  - gem uninstall bundler --all --force --executables
  - gem install bundler -v 1.12.5

script: rake spec:unit
