# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|
  config.vm.box = 'dummy'
  config.ssh.private_key_path = ENV['PRIVATE_KEY_PATH']

  config.vm.provider :oneandone do |oneandone|
    oneandone.name       = 'vagrant-test'
    oneandone.appliance  = 'ubuntu1604-64std'
    oneandone.datacenter = 'GB'
    oneandone.fixed_size = 'S'
  end

  config.vm.provision 'shell' do |s|
    s.inline = 'echo foobar'
  end
end
