# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|
  config.vm.box = 'dummy'
  config.ssh.private_key_path = '~/.ssh/id_rsa'

  config.vm.provider :oneandone do |server|
    server.name       = 'vagrant-coreos'
    server.appliance  = 'CoreOS_Stable_64std'
  end
end
