# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|
  config.vm.box = 'dummy'
  config.ssh.private_key_path = '~/.ssh/id_rsa'

  config.vm.define :centos do |centos|
    centos.ssh.pty = true
    centos.vm.provider :oneandone do |vm|
      vm.name        = 'worker1'
      vm.description = 'worker node 1'
      vm.appliance   = 'centos7-64std'
      vm.datacenter  = 'US'
    end
  end

  config.vm.define :ubuntu do |ubuntu|
    ubuntu.vm.provider :oneandone do |vm|
      vm.name        = 'worker2'
      vm.description = 'worker node 2'
      vm.appliance   = 'ubuntu1604-64std'
      vm.datacenter  = 'US'
    end
  end
end
